version: '3.9'
services:
  postgres:
    container_name: "optimization_task_3_postgres"
    hostname: 'postgres'
    image: 'postgres:14'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5434:5432"